name: SonarCloud | Asmar Sadikhova
on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Jacoco code coverage and run SonarCloud analysis
        run: ./gradlew sonarqube -Dsonar.projectKey=bhos-qa_lab-4-AsmarSad -Dsonar.organization=bhos-qa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
